# Generated by Django 3.2.4 on 2021-11-24 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='nombre')),
                ('estado', models.SmallIntegerField(default='1', verbose_name='estado')),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='nombre')),
                ('estado', models.SmallIntegerField(default='1', verbose_name='estado')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=15, verbose_name='cedula')),
                ('estado', models.SmallIntegerField(default='1', verbose_name='estado')),
                ('username', models.CharField(max_length=255, verbose_name='username')),
                ('contrasena', models.CharField(max_length=100, verbose_name='contrasena')),
                ('created_by', models.BigIntegerField(verbose_name='created_by')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.BigIntegerField(null=True, verbose_name='created_by')),
                ('updated_at', models.DateTimeField(null=True)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seproamerica.rol', verbose_name='rol')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=255, verbose_name='nombres')),
                ('apellidos', models.CharField(max_length=255, verbose_name='apellidos')),
                ('cedula', models.CharField(max_length=15, verbose_name='cedula')),
                ('celular', models.CharField(default='', max_length=15, verbose_name='cedula')),
                ('fecha_nacimiento', models.DateField(verbose_name='fecha_nacimiento')),
                ('direccion', models.CharField(default='', max_length=500, verbose_name='direccion')),
                ('estado', models.SmallIntegerField(default='1', verbose_name='estado')),
                ('created_by', models.BigIntegerField(verbose_name='created_by')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.BigIntegerField(null=True, verbose_name='created_by')),
                ('updated_at', models.DateTimeField(null=True)),
                ('profesion', models.CharField(max_length=255, null=True, verbose_name='profesion')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seproamerica.cargo', verbose_name='cargo')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='seproamerica.usuario', verbose_name='usuario')),
            ],
        ),
    ]
