# Generated by Django 3.2.4 on 2021-11-24 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seproamerica', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cargo',
            table='cargos',
        ),
        migrations.AlterModelTable(
            name='persona',
            table='personas',
        ),
        migrations.AlterModelTable(
            name='rol',
            table='rols',
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='usuarios',
        ),
    ]
