# Generated by Django 3.2.9 on 2021-11-24 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rol',
            options={'verbose_name_plural': 'roles'},
        ),
    ]
