# Generated by Django 3.2.9 on 2021-11-26 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0003_candadosatelital_vehiculo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candadosatelital',
            options={'verbose_name_plural': 'candados_satelitales'},
        ),
    ]
