# Generated by Django 3.2.9 on 2021-11-27 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0004_alter_candadosatelital_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='year',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='year'),
        ),
    ]
