# Generated by Django 3.2.9 on 2021-12-08 22:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0006_auto_20211128_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=255, verbose_name='nombre')),
            ],
            options={
                'verbose_name_plural': 'colores',
                'db_table': 'color',
            },
        ),
        migrations.CreateModel(
            name='MarcaVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=255, verbose_name='nombre')),
            ],
            options={
                'verbose_name_plural': 'marcas_vehiculo',
                'db_table': 'marca_vehiculo',
            },
        ),
        migrations.CreateModel(
            name='TipoVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=255, verbose_name='nombre')),
            ],
            options={
                'verbose_name_plural': 'tipos_vehiculo',
                'db_table': 'tipo_vehiculo',
            },
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='creator', to=settings.AUTH_USER_MODEL, verbose_name='created_by'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='created_date'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='deleted_date',
            field=models.DateField(null=True, verbose_name='deleted_date'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='is_deleted'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='modifier', to=settings.AUTH_USER_MODEL, verbose_name='modified_by'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='modified_date',
            field=models.DateField(default=datetime.date.today, verbose_name='deleted_date'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='observaciones',
            field=models.TextField(default='', verbose_name='observaciones'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='ruta_foto',
            field=models.CharField(default='', max_length=255, verbose_name='ruta_foto'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='cargo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='seguridad.cargo', verbose_name='cargo'),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='personaid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='seguridad.persona', verbose_name='personaid'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='persona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='seguridad.persona', verbose_name='personaid'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='seguridad.rol', verbose_name='rol'),
        ),
        migrations.AlterModelTable(
            name='candadosatelital',
            table='candado_satelital',
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='seguridad.color', verbose_name='color'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='marca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='seguridad.marcavehiculo', verbose_name='marca'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='seguridad.tipovehiculo', verbose_name='tipo'),
        ),
    ]
