# Generated by Django 3.2.9 on 2021-12-12 03:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0007_auto_20211208_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarcaCandadoSatelital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=255, verbose_name='nombre')),
            ],
            options={
                'verbose_name_plural': 'marcas_candado_satelital',
                'db_table': 'marca_candado_satelital',
            },
        ),
        migrations.CreateModel(
            name='TipoCandadoSatelital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=255, verbose_name='nombre')),
            ],
            options={
                'verbose_name_plural': 'tipos_candado_satelital',
                'db_table': 'tipo_candado_satelital',
            },
        ),
        migrations.AddField(
            model_name='candadosatelital',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='candado_satelital_creator', to=settings.AUTH_USER_MODEL, verbose_name='created_by'),
        ),
        migrations.AddField(
            model_name='candadosatelital',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='created_date'),
        ),
        migrations.AddField(
            model_name='candadosatelital',
            name='deleted_date',
            field=models.DateField(null=True, verbose_name='deleted_date'),
        ),
        migrations.AddField(
            model_name='candadosatelital',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='is_deleted'),
        ),
        migrations.AddField(
            model_name='candadosatelital',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='candado_satelital_modifier', to=settings.AUTH_USER_MODEL, verbose_name='modified_by'),
        ),
        migrations.AddField(
            model_name='candadosatelital',
            name='modified_date',
            field=models.DateField(default=datetime.date.today, verbose_name='modified_date'),
        ),
        migrations.AddField(
            model_name='candadosatelital',
            name='observaciones',
            field=models.TextField(default='', verbose_name='observaciones'),
        ),
        migrations.AddField(
            model_name='candadosatelital',
            name='ruta_foto',
            field=models.CharField(default='', max_length=255, verbose_name='ruta_foto'),
        ),
        migrations.AlterField(
            model_name='candadosatelital',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='seguridad.color', verbose_name='color'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='vehiculo_creator', to=settings.AUTH_USER_MODEL, verbose_name='created_by'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='vehiculo_modifier', to=settings.AUTH_USER_MODEL, verbose_name='modified_by'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='modified_date',
            field=models.DateField(default=datetime.date.today, verbose_name='modified_date'),
        ),
        migrations.AlterField(
            model_name='candadosatelital',
            name='marca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='seguridad.marcacandadosatelital', verbose_name='marca'),
        ),
        migrations.AlterField(
            model_name='candadosatelital',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='seguridad.tipocandadosatelital', verbose_name='tipo'),
        ),
    ]
