# Generated by Django 3.2.9 on 2021-11-28 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0008_alter_persona_fecha_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='@@seproamerica', max_length=255, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='persona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seguridad.persona', verbose_name='persona'),
        ),
    ]
