# Generated by Django 3.2.9 on 2021-12-14 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0008_auto_20211211_2214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=255, verbose_name='nombre')),
                ('recurso', models.PositiveSmallIntegerField(verbose_name='recurso')),
            ],
            options={
                'db_table': 'marca',
            },
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=255, verbose_name='nombre')),
                ('recurso', models.PositiveSmallIntegerField(verbose_name='recurso')),
            ],
            options={
                'db_table': 'tipo',
            },
        ),
        migrations.AlterField(
            model_name='candadosatelital',
            name='marca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='seguridad.marca', verbose_name='marca'),
        ),
        migrations.AlterField(
            model_name='candadosatelital',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='seguridad.tipo', verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='marca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='seguridad.marca', verbose_name='marca'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='seguridad.tipo', verbose_name='tipo'),
        ),
        migrations.DeleteModel(
            name='MarcaCandadoSatelital',
        ),
        migrations.DeleteModel(
            name='MarcaVehiculo',
        ),
        migrations.DeleteModel(
            name='TipoCandadoSatelital',
        ),
        migrations.DeleteModel(
            name='TipoVehiculo',
        ),
    ]
