# Generated by Django 3.2.9 on 2021-12-14 21:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0009_auto_20211214_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalibreArma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=255, verbose_name='nombre')),
            ],
            options={
                'verbose_name_plural': 'calibres_arma',
                'db_table': 'calibre_arma',
            },
        ),
        migrations.CreateModel(
            name='ModeloCelular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=255, verbose_name='nombre')),
            ],
            options={
                'verbose_name_plural': 'modelos_celular',
                'db_table': 'modelo_celular',
            },
        ),
        migrations.CreateModel(
            name='OperadoraCelular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=255, verbose_name='nombre')),
            ],
            options={
                'verbose_name_plural': 'operadoras_celular',
                'db_table': 'operadora_celular',
            },
        ),
        migrations.CreateModel(
            name='Celular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, null=True, verbose_name='created_date')),
                ('deleted_date', models.DateField(null=True, verbose_name='deleted_date')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='is_deleted')),
                ('modified_date', models.DateField(default=datetime.date.today, verbose_name='modified_date')),
                ('numero_contacto', models.CharField(default='', max_length=10, verbose_name='numero_contacto')),
                ('observaciones', models.TextField(default='', verbose_name='observaciones')),
                ('ruta_foto', models.CharField(default='', max_length=255, verbose_name='ruta_foto')),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='seguridad.color', verbose_name='color')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='celular_creator', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('marca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='seguridad.marca', verbose_name='marca')),
                ('modelo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='seguridad.modelocelular', verbose_name='modelo')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='celular_modifier', to=settings.AUTH_USER_MODEL, verbose_name='modified_by')),
                ('operadora', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='seguridad.operadoracelular', verbose_name='operadora')),
            ],
            options={
                'verbose_name_plural': 'celulares',
                'db_table': 'celular',
            },
        ),
        migrations.CreateModel(
            name='Arma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, null=True, verbose_name='created_date')),
                ('deleted_date', models.DateField(null=True, verbose_name='deleted_date')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='is_deleted')),
                ('modified_date', models.DateField(default=datetime.date.today, verbose_name='modified_date')),
                ('observaciones', models.TextField(default='', verbose_name='observaciones')),
                ('ruta_foto', models.CharField(default='', max_length=255, verbose_name='ruta_foto')),
                ('calibre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='seguridad.calibrearma', verbose_name='calibre')),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='seguridad.color', verbose_name='color')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='arma_creator', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('marca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='seguridad.marca', verbose_name='marca')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='arma_modifier', to=settings.AUTH_USER_MODEL, verbose_name='modified_by')),
                ('tipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='seguridad.tipo', verbose_name='tipo')),
            ],
            options={
                'db_table': 'arma',
            },
        ),
    ]
